<a href="https://colab.research.google.com/github/ramanath-naik/machine_learning/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas

In [1]:
import pandas as pd
import numpy as np


In [2]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
#create Dataframe
df = pd.DataFrame(data = np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])
print(df)
type(df)

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19


pandas.core.frame.DataFrame

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [7]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [8]:
##indexing
#columnname, rowindex[loc],rowindex number columnindex number [.iloc]

df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [17]:
df['Column1']


Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64

In [18]:
type(df['Column1'])

pandas.core.series.Series

In [24]:
#using column name
df[['Column1','Column2','Column3']]


Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [20]:
type(df[['Column1','Column2','Column3']])

pandas.core.frame.DataFrame

In [23]:
#using loc
df.loc['Row3']
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [25]:
#using iloc
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [27]:
df.iloc[2:,1:]
df.iloc[2,1]

9

In [28]:
#convert dataframes into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [29]:
#basic opertion
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [30]:
df.isnull()

Column1  Column2  Column3  Column4
Row1    False    False    False    False
Row2    False    False    False    False
Row3    False    False    False    False
Row4    False    False    False    False
Row5    False    False    False    False

In [32]:
df['Column3'].value_counts()
df["Column3"].unique()

array([ 2,  6, 10, 14, 18])

In [33]:
df[df['Column2']>2]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [35]:
#Series
a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)
print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [38]:
calories = {"day1": 420, "day2": 380, "day3": 390}

var = pd.Series(calories)

print(var)

day1    420
day2    380
day3    390
dtype: int64


In [39]:
calories = {"day1": 420, "day2": 380, "day3": 390}

var2 = pd.Series(calories, index = ["day1", "day2"])

print(var2)

day1    420
day2    380
dtype: int64


StringIO And
Pandas read_csv

In [40]:
#Reading different data sources with help of pandas
#stringIO is in-memory file object
from io import StringIO


In [42]:
import pandas as pd

file_path = '/content/sample_data/top_tv_series.csv'
df = pd.read_csv(file_path)
df.head()

Title       Year Parental Rating  Rating Number of Votes  \
0   1. Game of Thrones  2011–2019           TV-MA     9.2            2.3M   
1      2. Breaking Bad  2008–2013           TV-MA     9.5            2.1M   
2   3. Stranger Things  2016–2025           TV-14     8.7            1.3M   
3           4. Friends  1994–2004           TV-14     8.9            1.1M   
4  5. The Walking Dead  2010–2022           TV-MA     8.1            1.1M   

                                         Description  
0  Nine noble families fight for control over the...  
1  A chemistry teacher diagnosed with inoperable ...  
2  When a young boy vanishes, a small town uncove...  
3  Follows the personal and professional lives of...  
4  Sheriff Deputy Rick Grimes wakes up from a com...

In [43]:
type(df)

pandas.core.frame.DataFrame

In [44]:
data=('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3')

In [45]:
type(data)

str

In [46]:
StringIO(data)

In [47]:
pd.read_csv(StringIO(data))

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [48]:
pd.read_csv(StringIO(data), usecols=['col1','col2'])

col1 col2
0    x    y
1    a    b
2    c    d

In [49]:
data2 = ('a,b,c,d\n'
          '1,2,3,4\n'
          '5,6,7,8\n'
          '9,10,11')

In [50]:
pd.read_csv(StringIO(data2))

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [52]:
df = pd.read_csv(StringIO(data2),dtype='object')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes


In [53]:
df.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [54]:
df['a'][0]

'1'